news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('list-news', views.news_list, name="news_list"),
    path('detail-news/<int:id>', views.news_detail, name="news_detail"),
    path('create-news', views.news_create, name="news_create"),
]

virus_pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepew_home.urls')),
    path('donate/', include('donasi.urls')),
    path('', include('news.urls')),
    path('', include('question.urls')),
    path('', include('rumah_sakit.urls')),
    path('', include('screening.urls')),
]

news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField('Judul', max_length=255)
    source = models.CharField('Sumber', max_length=255)
    image_url = models.CharField('URL Gambar', max_length=255)
    content = models.TextField('Konten')
    date = models.DateTimeField(auto_now_add=True)

news/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import News

class CreateNews(ModelForm):
    class Meta:
        model = News
        fields = ['title', 'source', 'image_url', 'content']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Lebih dari 5.000 Kasus Covid-19 dalam 2 Hari, Epidemiolog: Ini Belum yang Terburuk'}),
            'source': TextInput(attrs={'placeholder': 'https://www.kompas.com/'}),
            'image_url': TextInput(attrs={'placeholder': 'https://unsplash.com/'}),
            'content': Textarea(attrs={'placeholder': 'Tuliskan isi beritamu disini'})
        }

news/views.py
from django.shortcuts import render, redirect
from .models import News
from .forms import CreateNews

# Create your views here.
def news_list(request):
	#return list of news
	news = News.objects.all().order_by('date')
	return render(request, "pages/news-list.html", {'news' : news})

def news_detail(request, id):
	#return detail of news
	item = News.objects.filter(pk = id)
	if item.exists():
		return render(request, "pages/news-detail.html", {'news' : item.first()})
	# return halaman error id not found
	return render(request, "pages/404.html", {'message' : 'Berita tidak ditemukan!'})

def news_create(request):
	#create new news
	form = CreateNews(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		form.save()
		return redirect('news:news_list')
	return render(request, "pages/news-create.html", {'form' : form})
	

news/templates/pages/news-create.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h2 class="sub-title">Bagikan Berita Terbaru</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-group">
            <a class="btn pepew-button" href="{% url 'news:news_list' %}"><i class="fas fa-arrow-left"></i>Kembali</a>
            <input type="submit" value="Simpan" class="btn pepew-button">
        </div>
    </form>
</main>
{% endblock content %}

news/templates/pages/news-detail.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <div class="image-section">
        <img class="news-img" src="{{ news.image_url }}" alt="News's image">
    </div>
    <h2 class="news-title">{{ news.title }}</h2>
    <p class="news-date">{{ news.date }}</p>
    <div class="blue-line"></div>
    <p class="news-content">{{ news.content }}</p>
    <p class="news-source">Sumber : {{ news.source }}</p>
    <div class="button-group">
        <a class="btn pepew-button" href="{% url 'news:news_list' %}"><i class="fas fa-arrow-left"></i>Kembali</a>
    </div>
</main>
{% endblock content %}

news/templates/pages/news-list.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<div id="news-hero" class="hero">
    <h1>Berita</h1>
</div>

<main class="container">
    <div id="question">
        <h2>Ingin menambahkan berita baru ?</h2>
        <div class="button-group">
            <a class="btn pepew-button" href="{% url 'news:news_create' %}">Tulis</a>
        </div>
    </div>
    
    <div id="news-grid">
        {% for item in news %}
        <a href="{% url 'news:news_detail' item.id %}">
            <div class="card">
                <img class="card-img-top" src="{{item.image_url}}" alt="News's image">
                <p class="date">{{ item.date }}</p>
                <h3 class="card-title">{{ item.title }}</h3>
            </div>
        </a>
        {% empty %}
            <!-- mau kasih image gitu -->
            <h3>Belum ada berita😟</h3>
        {% endfor %}
    </div>
</main>
{% endblock content %}